
###
POST http://localhost:5000/api/superheroes/heroes
Content-Type: application/json 

{"listN": "Mylist",
 "superhero": 
 [{
    "id":"10",
    "name": "Animl Man",
    "Gender": "Male",
    "Eyecolor": "bue",
    "Race": "Human",
    "Haircolor": "Blond",
    "Height": "0",
    "Publisher": "DC Comics",
    "Skincolor": "-",
    "Alignment": "good",
    "Weight": "0"
    }]  
}